embroider-build/content-tag

- src/snippets.rs
- src/transform.rs
You can see the change the easest in the diff for the test case. We went from: 
```js
class X {
static {
template("Hello", { eval() { return eval(arguments[0]) }}, this);
}
}
```
to: 
```js
class X {
static {
template("Hello", { component: this, eval() { return eval(arguments[0]) }});
}
}
```
> Move component `this` reference into first argument

- .github/workflows/release.yml
- CONTRIBUTING.md
- Cargo.toml
- LICENSE
- README.md
This PR also adds a few things that are nice for the release i.e. updating the readme to be about the consumers of the package and moving build instructions to a contributing.md file 👍
> Setup release on CI when tag is pushed

- .editorconfig
- .eslintrc.js
- .github/workflows/ci.yml
- .gitignore
- Cargo.lock
- Cargo.toml
- package-lock.json
- package.json
- src/bindings.rs
- src/lib.rs
- test/node-api.js
> Pass a better message back to JS

- src/transform.rs
We need to explicitly recurse in our transform handlers in order to make sure our transform applies in deeper parts of the AST.
> Fix: Inner expressions get missed

- Cargo.lock
- Cargo.toml
- sample/component.gjs
- src/bindings.rs
- src/lib.rs
- src/main.rs
- src/snippets.rs
- src/transform.rs
- test/node-api.js
This ensures that our transport is emitting good spans.
The rust-layer library now includes an option to append inline source maps, just because that was a straightforward way for me to test how our span-handling is working. It's not exposed to the JS bindings at this time.
> Initial sourcemapping support

- Cargo.lock
- Cargo.toml
- src/bindings.rs
- src/lib.rs
- src/test_helpers.rs
- test/node-api.js
fixes #19. We still need to review test assertions and do a fair bit of cleanup
> add Preprocessor.parse

- src/transform.rs
> Don't interpret js escapes in hbs

- CHANGELOG.md
According to the error in https://github.com/embroider-build/content-tag/actions/runs/7188581742/job/19578501105
The changelog needs a title that ends in `Changelog`
> Give the changelog a title

- .npmignore
Marking as `bug` because we have to publish over the 1.2.0 release because it's missing assets. 1.2.1 will have the built wasm files.
Problem revealed in https://github.com/embroider-build/content-tag/actions/runs/7201384902/job/19617380808#step:5:9 where the package is way too small, revealing wasm assets missing.
-------
According to `npm publish` docs: 
https://docs.npmjs.com/cli/v10/commands/npm-publish
> If there is a .gitignore or .npmignore file, then ignored files in that and all child directories will be excluded from the package. If both files exist, then the .gitignore is ignored, and only the .npmignore is used.
So this PR adds an `.npmignore` that _doesn't_ ignore the `pkg/node` and `pkg/standalone` folders.
We have `pkg/node/` and `pkg/standalone/` in the .gitignore because …
> Add .npmignore to not ignore pkg/* folders

- build.sh
- package.json
I've learned some things..
A difference between `npm` and `pnpm`.
`pnpm` (correct): runs lifecycle scripts on your own package regardless of your `ignore-scripts=true` in your `.npmrc`.
`npm` (incorrect): ignores all lifecycle scripts when `ignore-scripts=true` is present, including the obvious ones that you wrote yourself (as you'd define prepack in your own library to help with publishing). 
`ignore-scripts=true` was meant for _dependencies_ not your own package.... 
If you don't have `ignore-scirpts=true`:
```
npm pack
```
If you do have `ignore-scripts=true`:
```bash
npm run prepack
npm pack
```
_before this change_,
the built tgz is missing the pkg/node and pkg/standalone folders.
_after this change_,
the built tgz includes the pkg/node and pkg/standalone folders.
> Remove extraneous gitignores which interfere with packing

- Cargo.lock
- Cargo.toml
- package-lock.json
- package.json
- pkg/node.cjs
- pkg/standalone.js
- src/bindings.rs
- test/parse.test.js
- test/process.test.js
Fixes https://github.com/embroider-build/content-tag/issues/61
Right now I just added an extra argument to make it a non-braking change, but if you feel like we want to have second argument be an object that accepts the `filename: string` and `input_source_maps: bool`I can also change it to that
> Add js/rust bindings for inline source map generation

- index.d.ts
I missed that there is a type declarations file....
Only noticed once I tried to bump `content-tag` in other packages that ts was failing in those
> Update type declaration file with latest API

- test/process.test.js
This test wasn't really detecting the sourcemap comment because `equalCode` ignores comments.
> Fix sourcemap test

- pkg/node.cjs
- pkg/standalone.js
- src/bindings.rs
- test/process.test.js
The serde-based options handling isn't going to be able to accomodate callback types, which is something we want to add.
This is replacing it with a more hand-rolled `JsValue -> Options` conversion.
> Refactor options handling

- src/lib.rs
- test/process.test.js
> fix identifiers renaming

- index.d.cts
- package-lock.json
- package.json
When typescript is using moduleResolution:nodenext, our d.ts file is always treats as ESM due to our `type: "module"` in package.json.
But when we're actually providing a cjs implementation, we need typescript to see a cjs declaration file as well.
> Provide correct types when using cjs with moduleResolution:nodenext

- Cargo.lock
- Cargo.toml
- src/lib.rs
- src/test_helpers.rs
- test/process.test.js
- test/require.test.cjs
Fixes #71
After conversation with @wycats and reading @chancancode's comments in #71, it seems that our only concern here is making sure that the template import doesn't conflict. If we don't care about potentially importing multiple times (we can't see why we need to), then we can avoid the whole issue by always just importing it with a UUID.
> Strip hygiene code in favor of UUIDs

- index.d.cts
- index.d.ts
- package-lock.json
- src/bindings.rs
- src/lib.rs
- src/main.rs
- src/test_helpers.rs
- test/parse.test.js
- test/process.test.js
- test/require.test.cjs
Goal: make it so `@embroider/addon-dev` doesn't need another dependency to correctly handle sourcemaps:
https://github.com/embroider-build/embroider/pull/2162
Tested here:
- https://github.com/embroider-build/embroider/pull/2166
(success!)
> Change return type of process from string to { code, map }

- src/lib.rs
- src/test_helpers.rs
This will make content-tag builds reproducible, which is important to avoid unnecessary cache invalidation in production. The constant alias is sufficiently complex that it's extremely unlikely to clash with real user code.
Resolves #92
> Replace random import alias with constant

- Cargo.lock
- test/node/process.test.js
This bug can cause subtle and pretty surprising behavior, since dropping `declare` can change the way your field gets initialized.
The underlying swc printer bug is fixed upstream, and it looks like this would be fixed by upgrading. This fix just back ports the specific fix though because that's a quicker bug fix right now.
> content-tag accidentally strips "declare" keyword from class properties
